### ISSUE TITLE
As a music business owner, I want to have a homepage design that fits my personality and style of teaching (friendly, personal, engaging, direct). 

### ISSUE THREAD

**Issue by sophiekossmann1611** [Cathy-s-Piano-Studio-Wordpress/website#1]
**Description**
The site should attract in a friendly, engaging way. It should not look static, more so inviting.

**Overall Definition of Done**
Include picture(s) or video(s) that showcase the music business owner.

**Subtasks**
- [x] Select colour scheme of the website to match the overall feeling of the business.
Definition of Done: Colourscheme accepted by client.

- [x] Choose a fitting font and apply it consistently throughout all the website text.
Definition of Done: Font accepted by client.

- [x] Include picture(s) or video(s) that showcase the music business owner.
Definition of Done: Loading of images/videos on the side are checked by all 5 team members.

**Comment by GiuliaAndriuolo** [comment]
Wednesday 17-03-21
-Added logo to landing page 
-Added contact info 

![image](https://user-images.githubusercontent.com/79924976/111482449-33ada800-8734-11eb-9279-1d40b726deff.png)
![image](https://user-images.githubusercontent.com/79924976/111482504-3f996a00-8734-11eb-83a6-feb951f7b981.png)

**Comment by sofiacommandeur** [comment]
Sofia added missing content to the homepage (mostly text) & copyrights to photographer under the pictures

<img width="939" alt="Schermafbeelding 2021-03-18 om 13 09 15" src="https://user-images.githubusercontent.com/80045934/111623948-59e24f00-87eb-11eb-9a46-59ff157a22b9.png">
<img width="958" alt="Schermafbeelding 2021-03-18 om 13 09 23" src="https://user-images.githubusercontent.com/80045934/111623961-5c44a900-87eb-11eb-985e-df8ada7d2941.png">
<img width="964" alt="Schermafbeelding 2021-03-18 om 13 09 32" src="https://user-images.githubusercontent.com/80045934/111623972-5e0e6c80-87eb-11eb-8257-c668a798b0fd.png">

**Comment by sophiekossmann1611** [comment]
Buttons were adjusted to the original orange-pink
