### ISSUE TITLE
As an artist and experienced music teacher, I need to introduce myself and show my professional career path to enable potential new clients to get to know me better. 

### ISSUE THREAD

**Issue by GiuliaAndriuolo** [Cathy-s-Piano-Studio-Wordpress/website#3]
Description:
Cathy is curently using only linkedin to explain her professional and academic path, therefore it would be useful especially for prospective clients and colleagues to have an overview of her professional experience on the new website.

Definition of Done (DoD):
- A one page of her vita and a video of her introducing herself are added to the section
- A team member asks Cathy to provide some brief information in English language of her professional path and current activities (private teacher, teacher for talented students, orchestra), two team members select and approve the content and upload it
- A team member ask for Cathy's consent and add the basic information: telephone number, e-mail, where she lives are added by a team member

**Subtasks**

- [x] Create a subpage, containing multiple sections (including introduction, experience, education, social media and contact), which contain important information about Cathy.
- [x] Create an intriguing title for the page and add it to the top and add a slogan (one sentence) directly under the title and add motion effect for the slogan (Zoom in).  
- [x] Add a section with two columns, and place a picture of Cathy in the left column, and a text in the right one. Directly add a call-to-action button (Book free trial lesson) underneath the text. 
- [x] Add a section with two inner sections, who have three columns each. Add a title to the section (6 Golden Rules for Playing Piano) and text widgets for the 6 rules.  
- [x] Add a section with two columns, add a title to the right column (My education) and a list her different educations in the left one in a list with appealing and fitting icons. 
- [x] Add the last section, choose an exciting background picture and reduce opacity, add two inner sections. Add a title to the first inner section (Want to learn more about me or get in contact?), split second inner section in two columns and add a text field (Check out social media) and social media buttons (Facebook, Twitter, Youtube, Linkedin, Instagram)  in the left column and a text field (send me an email) and a link to open up an email to the right one.

**Comment by sophiekossmann1611** [comment]
Wednesday 10/03/20 WIP:
Created subpage with multiple sections:
Section 1 :1 column
- Title: About me 
- Textfield (two or three short sentences to start the page) 

Section 2: 2 columns
- left column: added edited picture of Cathy (round shape) 
- right column: Textfield (short welcome message) and added motion effect (zooming in) 

Section 3: 2 columns 
- left column: Title (H2) (My experience) 
- right column: text field 

Section 4: 2 columns
- left column: Icon list 
- right column: Title H2 (My education) 

Section 5: 1 column
- Title: Want to learn more about me or get in contact?
Subsection 2 columns
- left column: Textfield (Check out social media) + Social Media Buttons and Links
- right column: Textfield (Contact me) 

![image](https://user-images.githubusercontent.com/79995095/110656670-70bbec80-81c0-11eb-9cf5-417b27fbd8ae.png)

![image](https://user-images.githubusercontent.com/79995095/110656751-87fada00-81c0-11eb-8aff-0debc27bb245.png)

![image](https://user-images.githubusercontent.com/79995095/110658812-4d923c80-81c2-11eb-891a-e82d448f1cbb.png)

![image](https://user-images.githubusercontent.com/79995095/110656865-a3fe7b80-81c0-11eb-833e-d15a00c7cacc.png)

**Comment by sophiekossmann1611** [comment]
Giulia and Sophie are responsible for the technical set up of this subpage
Amina and Sofia are responsible for the specific content of this subpage

**Comment by AminaElJaadi** [comment]
New idea for the structure of this page:  At the top of the page we inculde Cathy's personal message and a picture. Then below this section, we have a section with a more marketing focus where we convince prospective students of the benefits of Cathy's lesson with the 6 golden rules. In this way we want to combine both the personal message of Cathy and the marketing goals that we want to achieve. 

Screenshots of the draft: 

![image](https://user-images.githubusercontent.com/80032113/110799823-e1740f00-827b-11eb-8755-bc8977057b63.png)

![image](https://user-images.githubusercontent.com/80032113/110799894-f0f35800-827b-11eb-9865-ec21b872948d.png)


We consider using the same structure for other pages.

**Comment by sophiekossmann1611** [comment]
Thursday 11/03 
Implemented Content and Design Idea of Amina (as shown above) for this subpage 

![image](https://user-images.githubusercontent.com/79995095/110801035-1e8cd100-827d-11eb-8237-5dc1575bf7a1.png)

![image](https://user-images.githubusercontent.com/79995095/110800597-a45c4c80-827c-11eb-8709-b888e6423efd.png)

![image](https://user-images.githubusercontent.com/79995095/110800657-b4742c00-827c-11eb-95de-e816ff331190.png)

![image](https://user-images.githubusercontent.com/79995095/110800686-be962a80-827c-11eb-8b42-b156e69fd1cc.png)

**Comment by sophiekossmann1611** [comment]
> Description:
> Cathy is curently using only linkedin to explain her professional and academic path, therefore it would be useful especially for prospective clients and colleagues to have an overview of her professional experience on the new website.
> 
> Definition of Done (DoD):
> 
> * A one page of her vita and a video of her introducing herself are added to the section
> * A team member asks Cathy to provide some brief information in English language of her professional path and current activities (private teacher, teacher for talented students, orchestra), two team members select and approve the content and upload it
> * A team member ask for Cathy's consent and add the basic information: telephone number, e-mail, where she lives are added by a team member
> 
> **Subtasks**
> 
> * [ ]  Create a subpage with a more detailed introduction to Cathy's career called "Bio"
> * [ ]  Immediately after the bio, insert the point of contact

### It was decided to change the subtasks of this user story in order to reflect the more-in depth content for the page which we were not aware of before. 
**New Subtasks are as follows:**  

- [ ] Create a subpage, containing multiple sections (including introduction, experience, education, social media and contact), which contain important information about Cathy.
- [ ] Create an intriguing title for the page and add it to the top and add a slogan (one sentence) directly under the title and add motion effect for the slogan (Zoom in).  
- [ ] Add a section with two columns, and place a picture of Cathy in the left column, and a text in the right one. Directly add a call-to-action button (Book free trial lesson) underneath the text. 
- [ ] Add a section with two inner sections, who have three columns each. Add a title to the section (6 Golden Rules for Playing Piano) and text widgets for the 6 rules.  
- [ ] Add a section with two columns, add a title to the right column (My education) and a list her different educations in the left one in a list with appealing and fitting icons. 
- [ ] Add the last section, choose an exciting background picture and reduce opacity, add two inner sections. Add a title to the first inner section (Want to learn more about me or get in contact?), split second inner section in two columns and add a text field (Check out social media) and social media buttons (Facebook, Twitter, Youtube, Linkedin, Instagram)  in the left column and a text field (send me an email) and a link to open up an email to the right one.

**Comment by GiuliaAndriuolo** [comment]
Wednesday 17-03-21
-I added contact info at the end of the subpage, as I have done to the other pages as well, keeping the same format.
-I added Cathy's logo close to the headline of the subpage. Keeping the same format of the other subpages.
-I tested social icons functioning and fixed non functioning call to action buttons

**Comment by sofiacommandeur** [comment]
Added video of Cathy playing

<img width="1102" alt="Schermafbeelding 2021-03-17 om 14 32 14" src="https://user-images.githubusercontent.com/80045934/111475859-d151a900-872d-11eb-8a88-21b90cb22ac0.png">

**Comment by sophiekossmann1611** [comment]
**Wednesday 17/03 - TOGETHER WITH GIULIA** 
- deleted the "my experience" section as it didn´t have any content yet and the client did not provide any content in this regard

**Comment by sophiekossmann1611** [comment]
Aligned the page with other subpages regarding design (e.g. buttons)
