### ISSUE TITLE
As a site visitor, I want to be able to navigate the site easily & intuitively. 

### ISSUE THREAD

**Issue by sophiekossmann1611** [Cathy-s-Piano-Studio-Wordpress/website#5]
**Description**
As Cathy offers lessons to all age groups, the site should be easy to navigate through and work intuitively, regardless of the one's age.

**General Definition of Done**
Tested by all 5 team members, Cathy and at least 4 of Cathy's current students to approve the ease of site.

**Subtasks**

- [x] Create a modular& plug-and-play architecture ( flexible system of standalone, reusable components as opposed to a static collection of pages) 
Definition of Done: Modularity of the website has been tested by 2 team members. Functioning has been shown and explained to Cathy and she feels confident to maintain the website by herself

- [x] Make the site accessible for a variety of devices (phone, laptop and tablet). 
Definition of Done: Tested by all 5 team members, using various devices. 

- [x] Add a navigation menu at the top with subpages.
Definition of Done: The navigation menu is installed and works, as tested by all 4 team members.

- [x] Keeping the subpages to a minimum, making sure there are not too many to choose from at the top.
Definition of Done: A maximum of six subpages are added to the navigation menu and tested by all 5 team members. 

- [x] Make sure that each page contains only relevant information, making each page not too long.
Definition of Done: A maximum of one time scrolling down through the text before reaching the end of the page is added, and checked by all 5 team members.

- [x] Use simple, efficient wording on each page.
Definition of Done: The texts are added using the chosen font and checked by all 5 team members.

- [x] Make all call for action buttons very visible and clear.
Definition of Done: Call for action buttons are clearly visible in regard to position, color use and font and checked by all 5 team members.

**Comment by sofiacommandeur** [comment]
Saturday 06/03/20 WIP:
Created homepage/landing page with:

- Navigation menu with 5 subtitles + (left) space for Logo
- Head-Image
- Title
- Subtitle
- Call for action button
- Subsection text + subimage "Who Am I"
- Subsection text + subimage "Products/Offerings"
- Subsection text + subimage "Events"
- Subsection text + subimage "Contact"
- Asked Cathy on Slack for possible slogan/quote options (See WIKI page)

<img width="1440" alt="Schermafbeelding 2021-03-06 om 17 21 07" src="https://user-images.githubusercontent.com/80045934/110213631-1dd0f500-7ea1-11eb-8297-097230d7a325.png">
<img width="1440" alt="Schermafbeelding 2021-03-06 om 17 21 05" src="https://user-images.githubusercontent.com/80045934/110213640-232e3f80-7ea1-11eb-8865-28a6af733ad2.png">
<img width="1440" alt="Schermafbeelding 2021-03-06 om 17 21 03" src="https://user-images.githubusercontent.com/80045934/110213644-25909980-7ea1-11eb-9730-2204f27c8327.png">
<img width="1440" alt="Schermafbeelding 2021-03-06 om 17 21 00" src="https://user-images.githubusercontent.com/80045934/110213646-275a5d00-7ea1-11eb-81ce-03c40f0f490d.png">

**Comment by borispham** [comment]
![contact c2a](https://user-images.githubusercontent.com/79994567/110252716-0b30eb80-7f87-11eb-924d-2b860002fe0e.png)
![end c2a](https://user-images.githubusercontent.com/79994567/110252719-0bc98200-7f87-11eb-8f92-b8e208f93689.png)
![frontpage](https://user-images.githubusercontent.com/79994567/110252720-0c621880-7f87-11eb-8b4d-a18d29a6cfdb.png)
![product c2a](https://user-images.githubusercontent.com/79994567/110252721-0c621880-7f87-11eb-9be7-49ddf787a749.png)
![slideshow](https://user-images.githubusercontent.com/79994567/110252722-0cfaaf00-7f87-11eb-9208-90ecd8011690.png)
![socials](https://user-images.githubusercontent.com/79994567/110252723-0cfaaf00-7f87-11eb-806c-751e53764418.png)
![testimonials](https://user-images.githubusercontent.com/79994567/110252724-0d934580-7f87-11eb-9fd1-f364efb729ca.png)

**Comment by sofiacommandeur** [comment]
Created new text (based on Cathy's own Wordpress tryouts) and added them to homepage, to see how the homepage looks with text:

<img width="1199" alt="Schermafbeelding 2021-03-10 om 14 41 26" src="https://user-images.githubusercontent.com/80045934/111044753-c5729800-844a-11eb-859e-cb9be2191470.png">
<img width="1192" alt="Schermafbeelding 2021-03-10 om 14 53 44" src="https://user-images.githubusercontent.com/80045934/111044761-cc99a600-844a-11eb-96ce-a76d0959c0f0.png">

**Comment by sophiekossmann1611** [comment]
**Wednesday 17/03** - **TOGETHER WITH GIULIA**
- updated the drop-down menu in regard to subpages 
- changed colour of font (from blue to white) in order to match the design of the site better 
- Set the landing page as the home page of the website, instead of the standard template
![image](https://user-images.githubusercontent.com/79995095/111598026-12e66080-87cf-11eb-92e8-af96171c8a76.png)

**Comment by sophiekossmann1611** [comment]
**Wednesday 17/03 - TOGETHER WITH GIULIA**

- adjusted bottom of the page section: deleted about column, added contact details
![image](https://user-images.githubusercontent.com/79995095/111599094-35c54480-87d0-11eb-8f87-684932b18335.png)
