### ISSUE TITLE
As a site visitor, I want the ability to easily schedule a trial session online with the music teacher.

### ISSUE THREAD

**Issue by sophiekossmann1611** [Cathy-s-Piano-Studio-Wordpress/website#6]
**Description**
Site visitors who are interested in taking a class with Cathy need an easy option to book a trial lesson without any issues. 

**General Definition of Done**
It is possible to book a trial session with Cathy directly on the homepage. 

**Subtasks**

- [x] Display Call to Action Button "Book a free trial/lesson now".
Definition of Done: Call 2 Action buttom is centered in each section of the page and linking to the funnel. Tested by 2 team members

- [x] Integrate a funnel with 3 basic questions
Definition of Done: Questions are accepted by Cathy, Funnel is working and has been tested by two team members.

- [x] Integrate contact information form
Definition of Done: Questions are accepted by Cathy, contact form is working and has been tested by two team members.

- [x] Place "send button"
Definition of Done: Button is on the page and is working. Tested by 3 team members. 

- [x] Implement a "Thank you page"
Definition of Done: automatically opening thank you page that is activated after form has been filled out. Tested by 2 team members.

**Comment by AminaElJaadi** [comment]
Possible questions for the funnel (input from meeting with Cathy): 

How old are you? 
Do you have previous experience with playing piano? (Yes/No) 
Which music genre do you like? (Different Genres) 
How often do you want to follow the lessons? (Once a week,  two times a week, …)

**Comment by borispham** [comment]
![funnel1](https://user-images.githubusercontent.com/79994567/110655200-21c18780-81bf-11eb-9821-f1c885148480.png)
![funnel2](https://user-images.githubusercontent.com/79994567/110655203-21c18780-81bf-11eb-97ce-9438a1b51b8c.png)
![funnel3](https://user-images.githubusercontent.com/79994567/110655205-225a1e00-81bf-11eb-927a-2ed0aa4fb792.png)
![thankyou2](https://user-images.githubusercontent.com/79994567/110655211-22f2b480-81bf-11eb-98d1-841bb51e0f92.png)
![Thankyou1](https://user-images.githubusercontent.com/79994567/110655214-22f2b480-81bf-11eb-9435-2e3572d748cd.png)

**Comment by borispham** [comment]
![contact page form](https://user-images.githubusercontent.com/79994567/111068618-d1516f00-84c9-11eb-8b14-1715aa89a78d.png)
