### ISSUE TITLE
As a site visitor, I would like to have an overview of the different products offered even before getting into contact with the piano teacher, so that I can select the one that best suits my needs.

### ISSUE THREAD

**Issue by AminaElJaadi** [Cathy-s-Piano-Studio-Wordpress/website#7]
**Description**
-
**General Definition of Done**
All subtasks are fulfilled. Two team members and the product owner has gone through the steps of reading the information, clicking themselves through the slideshow, answering the questions in the funnel, filling out the information form and being shown the Thank you page. 

**Subtasks** 

- [x] Add compelling heading to section 
      Definition of done: Text for heading has been accepted by product owner. 
      
- [x] Add small text field with short explanation of products. 
      Definition of done: Text has been accepted by product owner and checked by team member for spelling and readability. 
      
- [x] Slideshow of the different products (if she is offering them all already) 
      Definition of done: Slideshow is functioning and pictures are visible. 
      
- [x] Call to action button: Want to know a bit more? -> book trial 
       Definition of done: Button is linked to open up a pop-up funnel and tested by 2 team members. 
       
- [x] Implement funnel with 3 questions 
      Definition of done: Questions are accepted by Cathy, Funnel is working and has been tested. 
      
- [x] Integrate contact information form
      Definition of done: Questions are accepted by product owner. Filling out the contact information form has been tested by 
      two team members and the product owner. 
      
- [x] Place "send button"
       Definition of done: Button leads to sending the information entered and has been tested by two team members. 
       
- [x] Implement a "Thank you page"
       Definition of done: Thank you page automatically opens up after the contact information form has been sent, and this has 
       been tested by two team members.

**Comment by GiuliaAndriuolo** [comment]
Creation of "Product overview" subpage (WIP) - Tuesday 10/03/21:

Performed the following subtasks:

1. Created a clear and simple heading: "Product Overview".

2. Attached below the picture of Cathy's piano as placeholder. to show important part of the "product" (Would be great to add the video of the piano in the same place) 

3. Addition of a button "book free lesson" above the title and on the left to book the trial so that is clearly visible from the start.

4. Created 3 different sections at the beginning of the sub-page to show different target clients: kids, teenagers and adults

5. Attachment of photos of Cathy’s clients in the 3 sections to give an idea of the sense of community 

6. Right after the target clients section, creation of a column with the following captivating statement: “Can’t wait to join this amazing community?” to introduce the visitor to Cathy’s product in the following section.

7. Addition of a section for the explanation of different lessons’ formats offered by Cathy (mainly physical and digital). Added icons as bullet points.

8. Linked the subpage to the corresponding section in the homepage and tested it

9. Creation of Call to action button: “book free lesson” and added growth function to the button at the end of the sub-page

10. Insertion of a standard contact section “Want to learn more about me..”

11. Addition of social media contacts of Cathy and tested them 

![image](https://user-images.githubusercontent.com/79924976/110663681-f478d780-81c6-11eb-9eee-1f45b678bb6a.png)

![image](https://user-images.githubusercontent.com/79924976/110663865-27bb6680-81c7-11eb-9d12-2fca84df711e.png)

![image](https://user-images.githubusercontent.com/79924976/110663906-36098280-81c7-11eb-82ec-354540c38beb.png)

![image](https://user-images.githubusercontent.com/79924976/110664443-b03a0700-81c7-11eb-90e1-2858369b18f0.png)
 
![image](https://user-images.githubusercontent.com/79924976/110663975-4c174300-81c7-11eb-8c82-e1f0a4786361.png)

**Comment by sophiekossmann1611** [comment]
Giulia and Sophie are responsible for the technical set up of this subpage
Amina and Sofia are responsible for the specific content (especially text) of this subpage

**Comment by sofiacommandeur** [comment]
Text of the subpage inserted, created by Amina & Sofia

We added: 
1. Personal message of Cathy before presenting the products
2. Three columns with bullet points that describe the products
3. For each section we added sign up buttons  
4. Text for the different target groups
5. Contact information at the end of the page

<img width="1388" alt="Schermafbeelding 2021-03-13 om 22 09 59" src="https://user-images.githubusercontent.com/80045934/111044663-2c438180-844a-11eb-942d-e6620c01201c.png">
<img width="1096" alt="Schermafbeelding 2021-03-13 om 22 10 07" src="https://user-images.githubusercontent.com/80045934/111044660-2baaeb00-844a-11eb-8bef-99969044b893.png">
<img width="1111" alt="Schermafbeelding 2021-03-13 om 22 10 18" src="https://user-images.githubusercontent.com/80045934/111044659-2a79be00-844a-11eb-959b-c11b50cfd654.png">
<img width="1111" alt="Schermafbeelding 2021-03-13 om 22 10 27" src="https://user-images.githubusercontent.com/80045934/111044656-28affa80-844a-11eb-901b-29a76eac7d1d.png">
<img width="1103" alt="Schermafbeelding 2021-03-13 om 22 10 39" src="https://user-images.githubusercontent.com/80045934/111044651-22ba1980-844a-11eb-9902-3aa8d6786530.png">

**Comment by GiuliaAndriuolo** [comment]
Wednesday 17-03-21:

-I have changed the intro picture and substituted it by a video of Cathy's piano that plays by itself and a picture of the whole piano and Cathy's piano studio so that the general visitor can have at the same time a close view to the instrument and a broader view on the studio. 
The video is very short and starts automatically when the page is loaded.
-I added contact info at the end of the subpage, as I have done to the other pages as well, keeping the same format.
-I added Cathy's logo close to the headline of the subpage. Keeping the same format of the other subpages.
-I tested social icons functioning and fixed non functioning call to action buttons 

![image](https://user-images.githubusercontent.com/79924976/111481799-994d6480-8733-11eb-9f65-07e02b724869.png)
![image](https://user-images.githubusercontent.com/79924976/111481868-a9654400-8733-11eb-9fb3-e9cbeaa145be.png)

**Comment by sophiekossmann1611** [comment]
**Wedneday 17/03**
- created new suggestion for heading of page 
- added statement to the top 
- changed button colour to match logo 
![image](https://user-images.githubusercontent.com/79995095/111596519-8a1af500-87cd-11eb-9972-4f74b72da7e4.png)


- edited "what package do you like" section to match the overall layout and style of the page 
![image](https://user-images.githubusercontent.com/79995095/111596658-ad45a480-87cd-11eb-9489-b9168d768aa5.png)


- edited the "contact me" section in order to align it with other pages 
![image](https://user-images.githubusercontent.com/79995095/111596764-cd756380-87cd-11eb-9df8-deed59cc609f.png)
