### ISSUE TITLE
As a site visitor I would like to see who is already part of Cathy's piano community, so that it motivates me to subscribe as well.

### ISSUE THREAD

**Issue by AminaElJaadi** [Cathy-s-Piano-Studio-Wordpress/website#8]
**Description**
This is an idea for a new product which is currently not a product of Cathy and came up during the interviews. At the page of events "community feeling" to get people to wanting to be apart of that community. So marketing POV. 

**General definition of done** 
All the subtasks are done

**Subtasks** 

- [ ] Create a section for pictures, videos, statements about the piano lessons community
      Definition of done: Section is created 
      
- [ ] Collect and select relevant content
      Definition of done: Content for the page is selected
      
- [ ] Determine the layout of this section 
      Definition of done: Lay-out is selected and tested by 3 team members and reported as clear. 

- [ ] Add the content to the page
       Definition of done: Content is visible on the page and videos are working 

- [ ] Link the page to the button "Book a trial lesson and get an impression" on the home page 
       Definition of done: 3 team members clicked on the button and see the right page
