### ISSUE TITLE
As a site visitor, I would like to easily recognize the hyperlinks to Cathy's communication channels so that I can easily find additional information and social media channels.  

### ISSUE THREAD

**Issue by AminaElJaadi** [Cathy-s-Piano-Studio-Wordpress/website#9]
**Description** 
Section should include links to Facebook, Instagram, Linkedin , Youtube

**General definition of done**
All the subtasks are done 

**Subtasks** 

- [x] Create a social media section at the bottom of the home page 
       Definition of done: Section is created that fits the layout of the home page
       
- [x] Add matching buttons of the social networks 
        Definition of done: Buttons are created using the icons of the social networks

- [x] Add hyperlinks to the buttons of: - Facebook - Instagram - Linkedin -Youtube
       Definition of done: Hyperlinked icons are incorporated at the bottom of the page which have been tested by 3 team 
       members by clicking on the icon and are reported as working when access to the social networks is possible.

**Comment by GiuliaAndriuolo** [comment]
Wednesday 17-03-21:
-Tested social icons in all the pages
